"""add product details JSONB

Revision ID: 2b5609d7ac8d
Revises: da4bda4aabd0
Create Date: 2025-05-06 12:13:53.372586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b5609d7ac8d'
down_revision: Union[str, None] = 'da4bda4aabd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_urls', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('products', sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'details')
    op.drop_column('products', 'image_urls')
    # ### end Alembic commands ###
