"""add created at col to cart item

Revision ID: 2d0fb259d9f0
Revises: b154b8cd2453
Create Date: 2025-02-19 18:04:16.852574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d0fb259d9f0'
down_revision: Union[str, None] = 'b154b8cd2453'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart_items', 'created_at')
    # ### end Alembic commands ###
