"""remove enrichment cart schema

Revision ID: 331c85a7e010
Revises: 54b8f23fe967
Create Date: 2025-02-13 17:59:14.192521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '331c85a7e010'
down_revision: Union[str, None] = '54b8f23fe967'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
