"""Add featured column to products

Revision ID: 4f6d724baaa8
Revises: 8efce1d1af71
Create Date: 2025-03-05 12:04:37.647860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f6d724baaa8'
down_revision: Union[str, None] = '8efce1d1af71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('featured', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'featured')
    # ### end Alembic commands ###
