"""Add guest_email and guest_name to orders

Revision ID: 6b7163c31a69
Revises: 04ee16efc046
Create Date: 2025-06-10 17:16:28.215615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b7163c31a69'
down_revision: Union[str, None] = '04ee16efc046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('guest_name', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('guest_email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'guest_email')
    op.drop_column('orders', 'guest_name')
    # ### end Alembic commands ###
