"""Add contact tables

Revision ID: 6eed7d5c923a
Revises: 1da41e0fbbbf
Create Date: 2025-08-05 17:33:37.395776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6eed7d5c923a'
down_revision: Union[str, None] = '1da41e0fbbbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultation_bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('consultation_type', sa.String(length=50), nullable=False),
    sa.Column('preferred_date', sa.DateTime(), nullable=True),
    sa.Column('alternative_dates', sa.JSON(), nullable=True),
    sa.Column('duration_requested', sa.Integer(), nullable=True),
    sa.Column('project_description', sa.Text(), nullable=True),
    sa.Column('budget_range', sa.String(length=50), nullable=True),
    sa.Column('timeline', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('confirmed_date', sa.DateTime(), nullable=True),
    sa.Column('meeting_link', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultation_bookings_id'), 'consultation_bookings', ['id'], unique=False)
    op.create_table('contact_inquiries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('budget_range', sa.String(length=50), nullable=True),
    sa.Column('timeline', sa.String(length=50), nullable=True),
    sa.Column('preferred_location', sa.String(length=100), nullable=True),
    sa.Column('preferred_contact', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('response_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_inquiries_id'), 'contact_inquiries', ['id'], unique=False)
    op.create_table('location_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('location_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_notifications_id'), 'location_notifications', ['id'], unique=False)
    op.alter_column('cart_items', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index('idx_cart_items_user_id', table_name='cart_items')
    op.drop_index('idx_custom_order_images_order_id', table_name='custom_order_images')
    op.create_index(op.f('ix_custom_order_images_id'), 'custom_order_images', ['id'], unique=False)
    op.drop_constraint('custom_order_images_custom_order_id_fkey', 'custom_order_images', type_='foreignkey')
    op.create_foreign_key(None, 'custom_order_images', 'custom_orders', ['custom_order_id'], ['id'])
    op.alter_column('custom_order_timeline', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('custom_order_timeline', 'estimated_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('custom_order_timeline', 'is_completed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index('idx_custom_order_timeline_order_id', table_name='custom_order_timeline')
    op.create_index(op.f('ix_custom_order_timeline_id'), 'custom_order_timeline', ['id'], unique=False)
    op.drop_constraint('custom_order_timeline_custom_order_id_fkey', 'custom_order_timeline', type_='foreignkey')
    op.create_foreign_key(None, 'custom_order_timeline', 'custom_orders', ['custom_order_id'], ['id'])
    op.alter_column('custom_orders', 'target_completion',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('custom_orders', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'inquiry'::character varying"))
    op.alter_column('custom_orders', 'priority',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'standard'::character varying"))
    op.alter_column('custom_orders', 'last_contact_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('custom_orders', 'current_step',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('custom_orders', 'is_draft',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('custom_orders', 'form_completion_percentage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('custom_orders', 'marketing_consent',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index('idx_custom_orders_created_at', table_name='custom_orders')
    op.drop_index('idx_custom_orders_email', table_name='custom_orders')
    op.drop_index('idx_custom_orders_is_draft', table_name='custom_orders')
    op.drop_index('idx_custom_orders_priority', table_name='custom_orders')
    op.drop_index('idx_custom_orders_status', table_name='custom_orders')
    op.alter_column('design_consultations', 'scheduled_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('design_consultations', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'scheduled'::character varying"))
    op.drop_index('idx_design_consultations_order_id', table_name='design_consultations')
    op.drop_index('idx_design_consultations_scheduled_date', table_name='design_consultations')
    op.create_index(op.f('ix_design_consultations_id'), 'design_consultations', ['id'], unique=False)
    op.drop_constraint('design_consultations_custom_order_id_fkey', 'design_consultations', type_='foreignkey')
    op.create_foreign_key(None, 'design_consultations', 'custom_orders', ['custom_order_id'], ['id'])
    op.drop_index('idx_notification_preferences_frequency', table_name='notification_preferences')
    op.drop_index('idx_notification_preferences_user_id', table_name='notification_preferences')
    op.drop_constraint('uq_notification_preferences_user_id', 'notification_preferences', type_='unique')
    op.create_index(op.f('ix_notification_preferences_id'), 'notification_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=True)
    op.alter_column('products', 'inventory_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('idx_user_settings_category', table_name='user_settings')
    op.drop_index('idx_user_settings_setting_key', table_name='user_settings')
    op.drop_index('idx_user_settings_user_id', table_name='user_settings')
    op.create_index(op.f('ix_user_settings_id'), 'user_settings', ['id'], unique=False)
    op.create_index(op.f('ix_user_settings_setting_category'), 'user_settings', ['setting_category'], unique=False)
    op.create_index(op.f('ix_user_settings_setting_key'), 'user_settings', ['setting_key'], unique=False)
    op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index('idx_users_clerk_id', table_name='users')
    op.drop_index('idx_users_is_active', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_users_is_active', 'users', ['is_active'], unique=False)
    op.create_index('idx_users_clerk_id', 'users', ['clerk_id'], unique=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings')
    op.drop_index(op.f('ix_user_settings_setting_key'), table_name='user_settings')
    op.drop_index(op.f('ix_user_settings_setting_category'), table_name='user_settings')
    op.drop_index(op.f('ix_user_settings_id'), table_name='user_settings')
    op.create_index('idx_user_settings_user_id', 'user_settings', ['user_id'], unique=False)
    op.create_index('idx_user_settings_setting_key', 'user_settings', ['setting_key'], unique=False)
    op.create_index('idx_user_settings_category', 'user_settings', ['setting_category'], unique=False)
    op.alter_column('products', 'inventory_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_index(op.f('ix_notification_preferences_id'), table_name='notification_preferences')
    op.create_unique_constraint('uq_notification_preferences_user_id', 'notification_preferences', ['user_id'])
    op.create_index('idx_notification_preferences_user_id', 'notification_preferences', ['user_id'], unique=False)
    op.create_index('idx_notification_preferences_frequency', 'notification_preferences', ['notification_frequency'], unique=False)
    op.drop_constraint(None, 'design_consultations', type_='foreignkey')
    op.create_foreign_key('design_consultations_custom_order_id_fkey', 'design_consultations', 'custom_orders', ['custom_order_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_design_consultations_id'), table_name='design_consultations')
    op.create_index('idx_design_consultations_scheduled_date', 'design_consultations', ['scheduled_date'], unique=False)
    op.create_index('idx_design_consultations_order_id', 'design_consultations', ['custom_order_id'], unique=False)
    op.alter_column('design_consultations', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'scheduled'::character varying"))
    op.alter_column('design_consultations', 'scheduled_date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.create_index('idx_custom_orders_status', 'custom_orders', ['status'], unique=False)
    op.create_index('idx_custom_orders_priority', 'custom_orders', ['priority'], unique=False)
    op.create_index('idx_custom_orders_is_draft', 'custom_orders', ['is_draft'], unique=False)
    op.create_index('idx_custom_orders_email', 'custom_orders', ['email'], unique=False)
    op.create_index('idx_custom_orders_created_at', 'custom_orders', ['created_at'], unique=False)
    op.alter_column('custom_orders', 'marketing_consent',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('custom_orders', 'form_completion_percentage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('custom_orders', 'is_draft',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('custom_orders', 'current_step',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('custom_orders', 'last_contact_date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('custom_orders', 'priority',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'standard'::character varying"))
    op.alter_column('custom_orders', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'inquiry'::character varying"))
    op.alter_column('custom_orders', 'target_completion',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_constraint(None, 'custom_order_timeline', type_='foreignkey')
    op.create_foreign_key('custom_order_timeline_custom_order_id_fkey', 'custom_order_timeline', 'custom_orders', ['custom_order_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_custom_order_timeline_id'), table_name='custom_order_timeline')
    op.create_index('idx_custom_order_timeline_order_id', 'custom_order_timeline', ['custom_order_id'], unique=False)
    op.alter_column('custom_order_timeline', 'is_completed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('custom_order_timeline', 'estimated_date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('custom_order_timeline', 'completed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_constraint(None, 'custom_order_images', type_='foreignkey')
    op.create_foreign_key('custom_order_images_custom_order_id_fkey', 'custom_order_images', 'custom_orders', ['custom_order_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_custom_order_images_id'), table_name='custom_order_images')
    op.create_index('idx_custom_order_images_order_id', 'custom_order_images', ['custom_order_id'], unique=False)
    op.create_index('idx_cart_items_user_id', 'cart_items', ['user_id'], unique=False)
    op.alter_column('cart_items', 'user_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_location_notifications_id'), table_name='location_notifications')
    op.drop_table('location_notifications')
    op.drop_index(op.f('ix_contact_inquiries_id'), table_name='contact_inquiries')
    op.drop_table('contact_inquiries')
    op.drop_index(op.f('ix_consultation_bookings_id'), table_name='consultation_bookings')
    op.drop_table('consultation_bookings')
    # ### end Alembic commands ###
