"""change order table to include clerk_id instead of email

Revision ID: 8efce1d1af71
Revises: 2d0fb259d9f0
Create Date: 2025-02-19 18:11:20.297486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8efce1d1af71'
down_revision: Union[str, None] = '2d0fb259d9f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('user_id', sa.String(), nullable=False))
    op.drop_column('orders', 'user_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('user_email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('orders', 'user_id')
    # ### end Alembic commands ###
