"""Try Again alembic upgrade head

Revision ID: 918c62b9f0f6
Revises: 9251457f9037
Create Date: 2025-02-08 13:06:57.464272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '918c62b9f0f6'
down_revision: Union[str, None] = '9251457f9037'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
