"""Add category column

Revision ID: ac94aaf61d9c
Revises: e568420ae8f1
Create Date: 2025-02-09 11:03:37.942384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac94aaf61d9c'
down_revision: Union[str, None] = 'e568420ae8f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category', sa.String(), nullable=False))
    op.drop_column('products', 'test_col_2')
    op.drop_column('products', 'test_col')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('test_col', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('test_col_2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('products', 'category')
    # ### end Alembic commands ###
