"""remove enrichment cart schema

Revision ID: aed2aa801e08
Revises: e27cb85a0b41
Create Date: 2025-02-13 15:12:03.924266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aed2aa801e08'
down_revision: Union[str, None] = 'e27cb85a0b41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart_items', 'product_price')
    op.drop_column('cart_items', 'product_name')
    op.drop_column('cart_items', 'product_image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('product_image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cart_items', sa.Column('product_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('cart_items', sa.Column('product_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
