"""Add display_theme to products

Revision ID: b683a4a0c81f
Revises: fc476b073de3
Create Date: 2025-06-20 16:15:09.429786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b683a4a0c81f'
down_revision: Union[str, None] = 'fc476b073de3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('display_theme', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'display_theme')
    # ### end Alembic commands ###
