"""make featured col required

Revision ID: da4bda4aabd0
Revises: 4f6d724baaa8
Create Date: 2025-03-05 12:35:09.509358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da4bda4aabd0'
down_revision: Union[str, None] = '4f6d724baaa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'featured',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'featured',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
