"""Enhance order models

Revision ID: e244e9775d80
Revises: b683a4a0c81f
Create Date: 2025-07-22 12:31:41.925460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e244e9775d80'
down_revision: Union[str, None] = 'b683a4a0c81f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=True),
    sa.Column('to_status', sa.String(length=50), nullable=False),
    sa.Column('changed_by', sa.String(length=255), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_status_history_id'), 'order_status_history', ['id'], unique=False)
    op.add_column('order_items', sa.Column('product_sku', sa.String(length=100), nullable=True))
    op.add_column('order_items', sa.Column('product_description', sa.Text(), nullable=True))
    op.add_column('order_items', sa.Column('product_image_url', sa.String(length=500), nullable=True))
    op.add_column('order_items', sa.Column('product_category', sa.String(length=100), nullable=True))
    op.add_column('order_items', sa.Column('line_total', sa.Float(), nullable=False))
    op.add_column('order_items', sa.Column('custom_options', sa.JSON(), nullable=True))
    op.add_column('order_items', sa.Column('item_status', sa.String(length=50), nullable=True))
    op.add_column('order_items', sa.Column('tracking_info', sa.JSON(), nullable=True))
    op.add_column('order_items', sa.Column('item_created_at', sa.DateTime(), nullable=True))
    op.add_column('order_items', sa.Column('item_updated_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('order_number', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('customer_first_name', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('customer_last_name', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('customer_email', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('customer_phone', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('payment_status', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('subtotal', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('tax_amount', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('shipping_amount', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('discount_amount', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('currency', sa.String(length=3), nullable=True))
    op.add_column('orders', sa.Column('promo_code', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('promo_discount', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('shipping_address', sa.JSON(), nullable=True))
    op.add_column('orders', sa.Column('billing_address', sa.JSON(), nullable=True))
    op.add_column('orders', sa.Column('shipping_method_id', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('shipping_method_name', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('shipping_tracking_number', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('estimated_delivery_date', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('actual_delivery_date', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('stripe_charge_id', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('payment_method_last4', sa.String(length=4), nullable=True))
    op.add_column('orders', sa.Column('payment_method_brand', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('order_notes', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('internal_notes', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('is_gift', sa.Boolean(), nullable=True))
    op.add_column('orders', sa.Column('gift_message', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('gift_wrapping', sa.Boolean(), nullable=True))
    op.add_column('orders', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('shipped_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('delivered_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('confirmation_email_sent', sa.Boolean(), nullable=True))
    op.add_column('orders', sa.Column('shipping_email_sent', sa.Boolean(), nullable=True))
    op.add_column('orders', sa.Column('delivery_email_sent', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_orders_customer_email'), 'orders', ['customer_email'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_email'), table_name='orders')
    op.drop_column('orders', 'delivery_email_sent')
    op.drop_column('orders', 'shipping_email_sent')
    op.drop_column('orders', 'confirmation_email_sent')
    op.drop_column('orders', 'delivered_at')
    op.drop_column('orders', 'shipped_at')
    op.drop_column('orders', 'updated_at')
    op.drop_column('orders', 'gift_wrapping')
    op.drop_column('orders', 'gift_message')
    op.drop_column('orders', 'is_gift')
    op.drop_column('orders', 'internal_notes')
    op.drop_column('orders', 'order_notes')
    op.drop_column('orders', 'payment_method_brand')
    op.drop_column('orders', 'payment_method_last4')
    op.drop_column('orders', 'stripe_charge_id')
    op.drop_column('orders', 'stripe_payment_intent_id')
    op.drop_column('orders', 'actual_delivery_date')
    op.drop_column('orders', 'estimated_delivery_date')
    op.drop_column('orders', 'shipping_tracking_number')
    op.drop_column('orders', 'shipping_method_name')
    op.drop_column('orders', 'shipping_method_id')
    op.drop_column('orders', 'billing_address')
    op.drop_column('orders', 'shipping_address')
    op.drop_column('orders', 'promo_discount')
    op.drop_column('orders', 'promo_code')
    op.drop_column('orders', 'currency')
    op.drop_column('orders', 'discount_amount')
    op.drop_column('orders', 'shipping_amount')
    op.drop_column('orders', 'tax_amount')
    op.drop_column('orders', 'subtotal')
    op.drop_column('orders', 'payment_status')
    op.drop_column('orders', 'customer_phone')
    op.drop_column('orders', 'customer_email')
    op.drop_column('orders', 'customer_last_name')
    op.drop_column('orders', 'customer_first_name')
    op.drop_column('orders', 'order_number')
    op.drop_column('order_items', 'item_updated_at')
    op.drop_column('order_items', 'item_created_at')
    op.drop_column('order_items', 'tracking_info')
    op.drop_column('order_items', 'item_status')
    op.drop_column('order_items', 'custom_options')
    op.drop_column('order_items', 'line_total')
    op.drop_column('order_items', 'product_category')
    op.drop_column('order_items', 'product_image_url')
    op.drop_column('order_items', 'product_description')
    op.drop_column('order_items', 'product_sku')
    op.drop_index(op.f('ix_order_status_history_id'), table_name='order_status_history')
    op.drop_table('order_status_history')
    # ### end Alembic commands ###
