"""enrich cart schema

Revision ID: e27cb85a0b41
Revises: cb7820f50aa2
Create Date: 2025-02-13 15:06:07.291012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e27cb85a0b41'
down_revision: Union[str, None] = 'cb7820f50aa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('product_name', sa.String(), nullable=False))
    op.add_column('cart_items', sa.Column('product_price', sa.Float(), nullable=False))
    op.add_column('cart_items', sa.Column('product_image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart_items', 'product_image_url')
    op.drop_column('cart_items', 'product_price')
    op.drop_column('cart_items', 'product_name')
    # ### end Alembic commands ###
