"""Create users table - with __init__.py fix

Revision ID: fc68baf39792
Revises: 2b2713c4fce9
Create Date: 2025-02-09 17:55:29.601200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc68baf39792'
down_revision: Union[str, None] = '2b2713c4fce9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
